before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/repositories/
language: groovy
env:
  global:
  - TERM=dumb
jdk:
  - oraclejdk8
script: ./gradlew check -Dgrails.env=test
after_success:
- ./gradlew cobertura coveralls
notifications:
  slack:
    secure: m7tLX+4nHW9/GAw7htMJOvDCPu847ETA2NlyTPu4FSEFlR4ZRlSbZHOcrQMmNm/x6BXboO+BpHOUNzQaeLnXvHOTBiJFHTRuUqefZRHlJeuwNMYE4HPbjokL2QujVrOpTnpdp/LHaTysKOpEqWVkIznZTnJRnx+cHRf90sGkUtQ=
